### PR TITLE
Changes to test the redirects across versions

### PR DESCRIPTION
**Pull request by vishal-biyani**

### CODE REVIEW

**Comment by vishal-biyani** [comment]
This PR addresses most of the issues mentioned in #60 - except that there is no work done to find any old version-specific pages.

The preview can be seen at https://deploy-preview-94--docs-fission-io.netlify.com/latest/usage/package/

**Comment by life1347** [comment]
1.  We need to add "noindex" to every old version index.html. Alternative is to use robots.txt with "disallow" https://moz.com/learn/seo/robotstxt
2. From the redirect file, looks like we are always redirected to latest version. If we decide to so, then please add old upgrade docs list in https://docs.fission.io/0.6.0/installation/upgrade/ to current docs manually since users have no way to visit old docs.

Or, I suggest to move old docs to "/archive/" directory. And redirect to archive line if the version number is provided.
```
https://docs.fission.io/latest/....
https://docs.fission.io/archive/<version>/.....
```

And use robots.txt to disabllow page index as suggested in point 1

**Comment by soamvasani** [comment]
I think if you're including the archives in the public site then every page needs noindex, not just the root.  Or you can use robots.txt to prevent indexing.

Like we discussed in the meeting, suggest removing `latest/` from the URL.  But you'll still have to redirect everything from `latest/` to the root directory (because /latest URLs used to work before and we should make sure we don't break them).

**Comment by avigailof** [comment]
i'm not as versed in GitHub, so apologies if i'm repeating stuff you've already listed. here are a couple of things i found:
(not related specifically to redirects, but as long as we're updating the docs...)
1. the Fission logo at the top left corner needs to be linked to https://fission.io
2. or, preferably, if you were able to include the website navigation header, that'll make it even easier for folks to get to the other sections
3. in the opening sentence on https://deploy-preview-94--docs-fission-io.netlify.com/latest/ would be nice to mention it is open source (along the lines of "Fssion is a fast, open source serverless framework for Kubernetes "

specifically about the URLs structure:
4. the 301 redirects from the old URLs to the new ones is CRITICAL- otherwise we lose ALL the SEO juice and traffic from all the various URLs already out there. i can't tell from Vishal's comment on the last PR if these are handled or not :)
5. i can't see how we implemented items #4 and #5 in #[60](https://github.com/fission/docs.fission.io/issues/60)- so let me know if you guys plan on that, or if it's tabled for a future upgrade. i do think docs usually need a footer to show which latest version the content relates to- to orient readers.

Additional stuff:
6. https://deploy-preview-94--docs-fission-io.netlify.com/latest/languages/ this page is missing internal links to the other chapters like you have for Using Fission (only Go is listed, no JVM, etc.)

thanks!!

**Comment by vishal-biyani** [comment]
Closing this in favor of https://github.com/fission/docs.fission.io/pull/100 (Rebasing was getting too complex)

**Pull request closed without merging**
